#!/bin/bash
# dvc_cat <file_path> to see the old version of a file from DVC experiments
# --exp experiment name. if not provided, use the random one (implementation as of now; later it should be changed to select the last one)
# --out output file. if not provided, create a temp file and delete it after use

while [[ $# -gt 0 ]]; do
  case $1 in
    --exp)
      EXP_NAME="$2"
      shift 2
      ;;
    --out)
      OUT_FILE="$2"
      shift 2
      ;;
    *)
      FILE_PATH="$1"
      shift
      ;;
  esac
done


if [ -z "$EXP_NAME" ]; then
  EXP_NAME=$(dvc exp list  | sed -e 's/.*\[\(.*\)\].*/\1/' | head -n2 | tail -n1)
fi

if [ -z "$OUT_FILE" ]; then
  DELETE_OUT_FILE=true
  RANDOM_STR=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 13 ; echo '')
  OUT_FILE="__temp_output_${RANDOM_STR}__.log"
fi

dvc get . $FILE_PATH  --rev $EXP_NAME  --out $OUT_FILE
echo -e "\e[32m"
cat $OUT_FILE
echo -e "\e[0m"
if [ "$DELETE_OUT_FILE" = true ]; then
  rm $OUT_FILE
fi

trap cleanup EXIT
cleanup() {
    echo -e "\e[0m"
}